[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor speed
monitor_speed = 115200

; Use our custom partition table defined below
; https://github.com/espressif/arduino-esp32/blob/master/tools/partitions/default.csv
; https://github.com/espressif/arduino-esp32/blob/master/tools/partitions/min_spiffs.csv
board_build.partitions = min_spiffs.csv
; default.csv # exceeded default so using min spiffss in above 

; Compile flags for industrial stability
build_flags =
    -D CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=1 ; Enables Anti-Brick rollback
    -D CORE_DEBUG_LEVEL=0                      ; Disables background ESP-IDF logging for production

; Automatically download these libraries before compiling
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    mathieucarbou/AsyncTCP @ ^3.3.2
    bblanchon/ArduinoJson @ ^6.21.5
    https://github.com/mikalhart/ESP32-OTA-Pull.git#v1.0.2

monitor_filters = esp32_exception_decoder    
